version: '3.7'

services:
  tester:
    image: curlimages/curl
    network_mode: service:nginx
    command: tail -f /dev/null
    working_dir: /tmp
    volumes:
      - ./scripts/_test-e2e.sh:/tmp/e2e.sh

  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    env_file: .env
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:9.6
    env_file: .env
