version: '3.7'

services:

  mainnetwork:
    image: alpine
    command: tail -f /dev/null
    expose:
      - "80"
    ports:
      - 80:80
      - 9000:9000
      - 5432:5432

  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: service:mainnetwork
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      target: devel
    command: npm run dev
    env_file: .env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    network_mode: service:mainnetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: ./start-reload.sh
    env_file: .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./backend:/usr/src/app
    network_mode: service:mainnetwork
    depends_on:
      - db

  db:
    image: postgres:9.6
    env_file: .env
    volumes:
      - pg-data:/val/lib/postgresql/data/

volumes:
  pg-data: {}
