version: '3.7'

services:
  backend:
    build:
      context: ./backend
      args:
        DEVEL: ${DEVEL-true}
    command: ./start-reload.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 9000:9000
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
  db:
    image: postgres:9.6
    env_file: .env
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - pg-data:/val/lib/postgresql/data/

volumes:
  pg-data: {}
