version: '3.7'

services:

  mainnetwork:
    image: alpine
    command: tail -f /dev/null
    expose:
      - "80"
    ports:
      - 80:80
      - 3000:3000
      - 9000:9000
      - 5432:5432

  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ./nginx/dev-index.html:/usr/share/nginx/html/index.html
    network_mode: service:mainnetwork

  mali-portal:
    build:
      context: ./mali-portal
      target: devel
    command: npm run dev
    environment:
      NEXT_PUBLIC_API_HOST: http://localhost:9000
    volumes:
      - ./mali-portal:/usr/src/app
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    network_mode: service:mainnetwork
    depends_on:
      - data-api

  data-api:
    build:
      context: ./data-api
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: ./start-reload.sh
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - ./data-api:/usr/src/app
    network_mode: service:mainnetwork
    depends_on:
      - db

  db:
    image: postgres:9.6
    volumes:
      - pg-data:/val/lib/postgresql/data/
    network_mode: service:mainnetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app

volumes:
  pg-data: {}
