kind: ConfigMap
apiVersion: v1
metadata:
  name: akvo-data-portals
  namespace: default
data:
  mapbox-token: pk.eyJ1IjoibWFydGluY2hyaXN0b3YiLCJhIjoiTXFhSVJTMCJ9.dsByYqa5jm2OU7KwrfV3vA
  domain: https://dataportals.akvotest.org